---
jobs:
  build:
    docker:
      - image: 'circleci/ruby:2.4.1-node'
        environment:
          AWS_REGION: "eu-west-2"
          MODULEPATH: '/home/ubuntu/.puppetlabs/etc/code/modules'
          PUPPET_APPLY_ARGS: "--verbose"
          PUPPET_ENVIRONMENT: "deuw2"
    steps:
      - checkout
#      -
#        restore_cache:
#          keys:
#            - "projectname-{{ .Branch }}-{{ checksum \"Gemfile\" }}"
#            - "projectname-{{ .Branch }}"
#            - projectname-master
      -
        run:
          command: "bundle install --path vendor/bundle"
          name: "Bundle Install"
      -
        run:
          command: "bundle clean --force"
          name: "Bundle Cleanup"
      -
        run:
          command: "bundle exec librarian-puppet install --path $MODULEPATH --clean --verbose"
          name: "Install Puppet modules"
      -
        save_cache:
          key: "projectname-{{ .Branch }}-{{ checksum \"Gemfile\" }}"
          paths:
            - vendor/bundle
            - $MODULEPATH
      -
        run:
          command: "bundle exec rake release_checks"
          name: "Release checks"
      -
        run:
          command: "bundle exec rake build"
          name: "Build the package"
      -
        deploy:
          name: Install build module and execute
          command: |
            puppet module install --verbose pkg/locp-awsiac-0.1.0.tar.gz
            FACTER_ENSURE=present puppet apply ${PUPPET_APPLY_ARGS} examples/init.pp
    working_directory: ~/puppet-awsiac
version: 2
